# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: angular/ngcontainer:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && yarn --version \
              && git --version
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run unit tests!
      # - run: yarn test

      # Build the libraries
      - run: yarn build:lib

      # Build the demo apps (from library packages)
      - run: yarn build:app

      # Store build artefacts on circle
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
          
    dependencies:
      pre:
        - echo "scope=ramiz4" >> ~/.npmrc
        - echo "@ramiz4:registry=https://registry.npmjs.org/" >> ~/.npmrc
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      
    deployment:
      npm:
        tag: /v[0-9]+(\.[0-9]+)*/
        commands:
          - npm publish dist/ngx-multi-level-push-menu/
