# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.20.8

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && npm --version \
              && git --version

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # - run:
      #     name: Run unit tests
      #     command: npm test

      - run:
          name: Build ngx-multi-level-push-menu
          command: npm run build:lib

      - store_artifacts:
          name: Store build artefacts on circle
          path: ~/repo/dist
          destination: dist

      - run:
          name: Verify NPM_TOKEN is set
          command: |
            if [ -z "$NPM_TOKEN" ]; then
              echo "ERROR: NPM_TOKEN is not set"
              exit 1
            else
              echo "NPM_TOKEN is set (value not shown for security)"
            fi

      - run:
          name: Configure npm for CI publishing
          command: |
            echo "registry=https://registry.npmjs.org/" > ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm config set access public

      - run:
          name: Publish package
          command: npm run publish:ci
