# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers
      
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Version Info
          command: |
            node --version \
              && yarn --version \
              && git --version

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # Run unit tests!
      # - run: yarn test

      # Build affected apps and libraries
      - run: yarn affected:build --all

      # Store build artefacts on circle
      - store_artifacts:
          path: ~/repo/dist
          destination: dist

  deploy:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set scope
          command: echo "scope=ramiz4" >> ~/repo/.npmrc
      - run:
          name: Set registry URL
          command: echo "@ramiz4:registry=https://registry.npmjs.org/" >> ~/repo/.npmrc
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish dist/libs/ngx-multi-level-push-menu/

workflows:
  version: 2
  only_build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
